$.getScript("http://addons2.margonem.pl/get/6/6838verified.js", function () {
  $('<div class="torba_dodatkow_item" id="helpbutton" ctip="t_item" tip="<b>Margonemski Przewodnik</b><b class=artefact>* artefakt *</b>Typ:  Książki<br><i class=idesc>Jest to książka która zawiera najważniejsze informacje związane z krainą Margonem</i>Związany z właścicielem<br>Wartość: 5.5k" ><div style="width:32px; height:32px; opacity: 0.75; background: url(http://img811.imageshack.us/img811/644/itbordersred.png);"><img src="http://game9.margonem.pl/obrazki/itemy/pap/ksiazka2.gif"></div></div>')
        .click(function () {
          	$('#books').show();
          	$('#book_t').html('<h1>Margonemski Przewodnik</h1>Władysław Jagiełło');
          	$('#book_c').html('<center><h1>Spis Treści</h1></center></br><b>Pomoc:</b><br>• <a href=http://pomoc.margonem.pl/index.php?a=art_show&val=1 target=_blank>Dokumentacja gry</a><br>• <a href=http://www.margonem.pl/?task=help target=_blank>FAQ</a><br>• <a href=http://pomoc.margonem.pl/index.php?a=art_show&val=61 target=_blank>Regulamin</a><br>• <a href=http://pomoc.margonem.pl/index.php?a=art_show&val=250 target=_blank>Etykieta gracza Margonem</a><br>• <a href=http://www.margonem.pl/?task=support target=_blank>Panel kontaktowy</a><br>• <a href=http://www.margonem.pl/?task=skills2 target=_blank>Lista Umiejętności</a><br>• <a href=http://www.margonem.pl/?task=art&id=9 target=_blank>Smocze Łzy</a><br></br><b>Pomoce tematy na forum:</b><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=327927 target=_blank>Herosi</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=381322 target=_blank>Elity</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=385345 target=_blank>Elity II</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=372864 target=_blank>Tytani</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=385795 target=_blank>Klątwy i Błogosławieństwa</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=96201 target=_blank>Rośliny, Owoce, Grzyby itp.</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=352827 target=_blank>Przedmioty za Smocze Łzy</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=370331 target=_blank>Oczyszczanie i łączenie itemów</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=380190 target=_blank>Czas trwania bonusów w przedmiotach legendarnych</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=316673 target=_blank>Gdzie expić?</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=134252 target=_blank>ABC questów</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=269290 target=_blank>Współrzędne NPC</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=349148 target=_blank>Kupcy i Sprzedawcy</a>');
        	$('#book_p').html('<span>1</span>/2');
          	$('#book_next').click(function () {
              $('#book_c').html('<b>Strony poświęcone Margonem:</b><br>• <a href=http://www.emargo.pl/ target=_blank>eMargo</a><br>• <a href=http://www.margonem-fansite.pl/ target=_blank>Margonem Fansite</a><br>• <a href=http://www.old-margo.pl/ target=_blank>Old Margo</a><br>• <a href=http://www.margoextend.net/ target=_blank>Margo Extend</a><br>• <a href=http://ezinrivendell.blogspot.com/ target=_blank>Goniec z Rievendell</a></br></br><b>Inne:</b></br>• <a href=http://www.margonem.pl/?task=news target=_blank>Nowości</a></br>• <a href=http://www.margonem.pl/?task=ladder target=_blank>Rankingi</a></br>• <a href=http://www.margonem.pl/?task=stats target=_blank>Statystyki</a></br>• <a href=http://www.margonem.pl/?task=forum target=_blank>Forum</a><br>');
        		$('#book_p').html('<span>2</span>/2');
              $('#book_prev').click(function () {
                $('#book_c').html('<center><h1>Spis Treści</h1></center></br><b>Pomoc:</b><br>• <a href=http://pomoc.margonem.pl/index.php?a=art_show&val=1 target=_blank>Dokumentacja gry</a><br>• <a href=http://www.margonem.pl/?task=help target=_blank>FAQ</a><br>• <a href=http://pomoc.margonem.pl/index.php?a=art_show&val=61 target=_blank>Regulamin</a><br>• <a href=http://pomoc.margonem.pl/index.php?a=art_show&val=250 target=_blank>Etykieta gracza Margonem</a><br>• <a href=http://www.margonem.pl/?task=support target=_blank>Panel kontaktowy</a><br>• <a href=http://www.margonem.pl/?task=skills2 target=_blank>Lista Umiejętności</a><br>• <a href=http://www.margonem.pl/?task=art&id=9 target=_blank>Smocze Łzy</a><br></br><b>Pomoce tematy na forum:</b><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=327927 target=_blank>Herosi</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=381322 target=_blank>Elity</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=385345 target=_blank>Elity II</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=372864 target=_blank>Tytani</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=385795 target=_blank>Klątwy i Błogosławieństwa</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=96201 target=_blank>Rośliny, Owoce, Grzyby itp.</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=352827 target=_blank>Przedmioty za Smocze Łzy</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=370331 target=_blank>Oczyszczanie i łączenie itemów</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=380190 target=_blank>Czas trwania bonusów w przedmiotach legendarnych</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=316673 target=_blank>Gdzie expić?</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=134252 target=_blank>ABC questów</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=269290 target=_blank>Współrzędne NPC</a><br>• <a href=http://www.margonem.pl/?task=forum&show=posts&id=349148 target=_blank>Kupcy i Sprzedawcy</a>');
              	$('#book_p').html('<span>1</span>/2');
              });
            });
        }).appendTo('#torba_dodatkow');
});